### ISSUE TITLE
Feature: Implement `TryFrom<f64>` to avoid panics.

### ISSUE THREAD

**Issue by metasim** [xpe/q-num#2]
It would be nice to complement the generated `From<f64>` implementation with a `TryFrom<f64>` version that allows runtime handling of overflow translation rather than having the risk of `panic` in deployed code.

**Comment by xpe** [comment]
@metasim Agreed. Would you have any time for a PR?

**Comment by metasim** [comment]
@xpe Yes, happy to, but it might be a breaking change. In `std` there's a blanket `TryFrom` for anything with an `Into` already.

```rust
impl<T, U> TryFrom<U> for T
where
    U: Into<T>, 
...
```

https://doc.rust-lang.org/src/core/convert/mod.rs.html#805-815

How do you feel about that?

**Comment by xpe** [comment]
@metasim We can bump the version for a breaking change. / `TryFrom` seems like a good thing to try. Thanks!
